language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t koyejin/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI
